version: '3.4'

services:
  investportfoliomanager-api:
    image: investportfoliomanagerapi
    build:
      context: .
      dockerfile: InvestPortfolioManager.API/Dockerfile
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=InvestPortfolioDb;User Id=sa;Password=Your_password123;TrustServerCertificate=True;
    depends_on:
      - rabbitmq
      - sqlserver

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  sqlserver:
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
